apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240623073501.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240623073501.0.0+build.6aff574
  releaseNotes: |
    Release v20240623073501.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-22-06-2024-20-59-19-280482737/where-for-dinner-my-apps-bundle@sha256:e5716c8e72785523667bf7436f7b5694bc173ad1d0b283aea31eef9e23e740fb
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

